# This file was auto-generated by Fern from our API Definition.

import typing
import urllib.parse
from json.decoder import JSONDecodeError

import httpx
import pydantic

from ...core.api_error import ApiError
from ...core.jsonable_encoder import jsonable_encoder
from ...core.remove_none_from_headers import remove_none_from_headers
from ...types.terminal_details import TerminalDetails
from ...types.terminal_response import TerminalResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SoftPosClient:
    def __init__(
        self,
        *,
        environment: str,
        client_id: typing.Optional[str] = None,
        client_secret: typing.Optional[str] = None,
        api_version: typing.Optional[str] = None,
    ):
        self._environment = environment
        self.client_id = client_id
        self.client_secret = client_secret
        self.api_version = api_version

    def create_terminals(
        self, *, terminal_id: typing.Optional[str] = OMIT, terminal_name: str, terminal_phone_no: str
    ) -> TerminalResponse:
        _request: typing.Dict[str, typing.Any] = {
            "terminal_name": terminal_name,
            "terminal_phone_no": terminal_phone_no,
        }
        if terminal_id is not OMIT:
            _request["terminal_id"] = terminal_id
        _response = httpx.request(
            "POST",
            urllib.parse.urljoin(f"{self._environment}/", "terminal"),
            json=jsonable_encoder(_request),
            headers=remove_none_from_headers(
                {
                    "x-client-id": self.client_id,
                    "x-client-secret": self.client_secret,
                    "x-api-version": self.api_version,
                }
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(TerminalResponse, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_terminal_by_mobile_number(self, terminal_phone_no: str) -> TerminalDetails:
        _response = httpx.request(
            "GET",
            urllib.parse.urljoin(f"{self._environment}/", f"terminal/{terminal_phone_no}"),
            headers=remove_none_from_headers(
                {
                    "x-client-id": self.client_id,
                    "x-client-secret": self.client_secret,
                    "x-api-version": self.api_version,
                }
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(TerminalDetails, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncSoftPosClient:
    def __init__(
        self,
        *,
        environment: str,
        client_id: typing.Optional[str] = None,
        client_secret: typing.Optional[str] = None,
        api_version: typing.Optional[str] = None,
    ):
        self._environment = environment
        self.client_id = client_id
        self.client_secret = client_secret
        self.api_version = api_version

    async def create_terminals(
        self, *, terminal_id: typing.Optional[str] = OMIT, terminal_name: str, terminal_phone_no: str
    ) -> TerminalResponse:
        _request: typing.Dict[str, typing.Any] = {
            "terminal_name": terminal_name,
            "terminal_phone_no": terminal_phone_no,
        }
        if terminal_id is not OMIT:
            _request["terminal_id"] = terminal_id
        async with httpx.AsyncClient() as _client:
            _response = await _client.request(
                "POST",
                urllib.parse.urljoin(f"{self._environment}/", "terminal"),
                json=jsonable_encoder(_request),
                headers=remove_none_from_headers(
                    {
                        "x-client-id": self.client_id,
                        "x-client-secret": self.client_secret,
                        "x-api-version": self.api_version,
                    }
                ),
                timeout=60,
            )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(TerminalResponse, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_terminal_by_mobile_number(self, terminal_phone_no: str) -> TerminalDetails:
        async with httpx.AsyncClient() as _client:
            _response = await _client.request(
                "GET",
                urllib.parse.urljoin(f"{self._environment}/", f"terminal/{terminal_phone_no}"),
                headers=remove_none_from_headers(
                    {
                        "x-client-id": self.client_id,
                        "x-client-secret": self.client_secret,
                        "x-api-version": self.api_version,
                    }
                ),
                timeout=60,
            )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(TerminalDetails, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
