# This file was auto-generated by Fern from our API Definition.

import typing
import urllib.parse
from json.decoder import JSONDecodeError

import httpx
import pydantic

from ...core.api_error import ApiError
from ...core.jsonable_encoder import jsonable_encoder
from ...core.remove_none_from_headers import remove_none_from_headers
from ...types.offer_details import OfferDetails
from ...types.offer_entity import OfferEntity
from ...types.offer_meta import OfferMeta
from ...types.offer_tnc import OfferTnc
from ...types.offer_validations import OfferValidations


class OffersClient:
    def __init__(
        self,
        *,
        environment: str,
        client_id: typing.Optional[str] = None,
        client_secret: typing.Optional[str] = None,
        api_version: typing.Optional[str] = None,
    ):
        self._environment = environment
        self.client_id = client_id
        self.client_secret = client_secret
        self.api_version = api_version

    def create_offer(
        self,
        *,
        offer_meta: OfferMeta,
        offer_tnc: OfferTnc,
        offer_details: OfferDetails,
        offer_validations: OfferValidations,
    ) -> OfferEntity:
        _response = httpx.request(
            "POST",
            urllib.parse.urljoin(f"{self._environment}/", "offers"),
            json=jsonable_encoder(
                {
                    "offer_meta": offer_meta,
                    "offer_tnc": offer_tnc,
                    "offer_details": offer_details,
                    "offer_validations": offer_validations,
                }
            ),
            headers=remove_none_from_headers(
                {
                    "x-client-id": self.client_id,
                    "x-client-secret": self.client_secret,
                    "x-api-version": self.api_version,
                }
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(OfferEntity, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def get_offer(self, offer_id: str) -> OfferEntity:
        _response = httpx.request(
            "GET",
            urllib.parse.urljoin(f"{self._environment}/", f"offers/{offer_id}"),
            headers=remove_none_from_headers(
                {
                    "x-client-id": self.client_id,
                    "x-client-secret": self.client_secret,
                    "x-api-version": self.api_version,
                }
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(OfferEntity, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncOffersClient:
    def __init__(
        self,
        *,
        environment: str,
        client_id: typing.Optional[str] = None,
        client_secret: typing.Optional[str] = None,
        api_version: typing.Optional[str] = None,
    ):
        self._environment = environment
        self.client_id = client_id
        self.client_secret = client_secret
        self.api_version = api_version

    async def create_offer(
        self,
        *,
        offer_meta: OfferMeta,
        offer_tnc: OfferTnc,
        offer_details: OfferDetails,
        offer_validations: OfferValidations,
    ) -> OfferEntity:
        async with httpx.AsyncClient() as _client:
            _response = await _client.request(
                "POST",
                urllib.parse.urljoin(f"{self._environment}/", "offers"),
                json=jsonable_encoder(
                    {
                        "offer_meta": offer_meta,
                        "offer_tnc": offer_tnc,
                        "offer_details": offer_details,
                        "offer_validations": offer_validations,
                    }
                ),
                headers=remove_none_from_headers(
                    {
                        "x-client-id": self.client_id,
                        "x-client-secret": self.client_secret,
                        "x-api-version": self.api_version,
                    }
                ),
                timeout=60,
            )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(OfferEntity, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def get_offer(self, offer_id: str) -> OfferEntity:
        async with httpx.AsyncClient() as _client:
            _response = await _client.request(
                "GET",
                urllib.parse.urljoin(f"{self._environment}/", f"offers/{offer_id}"),
                headers=remove_none_from_headers(
                    {
                        "x-client-id": self.client_id,
                        "x-client-secret": self.client_secret,
                        "x-api-version": self.api_version,
                    }
                ),
                timeout=60,
            )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(OfferEntity, _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
