# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.link_cancelled_error import LinkCancelledError


class BadRequestError(ApiError):
    def __init__(self, body: LinkCancelledError):
        super().__init__(status_code=400, body=body)
