# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.rate_limit_error import RateLimitError


class TooManyRequestsError(ApiError):
    def __init__(self, body: RateLimitError):
        super().__init__(status_code=429, body=body)
