# This file was auto-generated by Fern from our API Definition.

from ..core.api_error import ApiError
from ..types.authentication_error import AuthenticationError


class UnauthorizedError(ApiError):
    def __init__(self, body: AuthenticationError):
        super().__init__(status_code=401, body=body)
