# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .app_provider import AppProvider


class App(pydantic.BaseModel):
    channel: str = pydantic.Field(description=("Specify the channel through which the payment must be processed.\n"))
    provider: AppProvider = pydantic.Field(
        description=("Specify the provider through which the payment must be processed.\n")
    )
    phone: str = pydantic.Field(description=("Customer phone number associated with a wallet for payment.\n"))

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
