# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AppProvider(str, enum.Enum):
    """
    Specify the provider through which the payment must be processed.
    """

    GPAY = "gpay"
    PHONEPE = "phonepe"
    OLA = "ola"
    PAYTM = "paytm"
    AMAZON = "amazon"
    AIRTEL = "airtel"
    FREECHARGE = "freecharge"
    MOBIKWIK = "mobikwik"
    JIO = "jio"

    def visit(
        self,
        gpay: typing.Callable[[], T_Result],
        phonepe: typing.Callable[[], T_Result],
        ola: typing.Callable[[], T_Result],
        paytm: typing.Callable[[], T_Result],
        amazon: typing.Callable[[], T_Result],
        airtel: typing.Callable[[], T_Result],
        freecharge: typing.Callable[[], T_Result],
        mobikwik: typing.Callable[[], T_Result],
        jio: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is AppProvider.GPAY:
            return gpay()
        if self is AppProvider.PHONEPE:
            return phonepe()
        if self is AppProvider.OLA:
            return ola()
        if self is AppProvider.PAYTM:
            return paytm()
        if self is AppProvider.AMAZON:
            return amazon()
        if self is AppProvider.AIRTEL:
            return airtel()
        if self is AppProvider.FREECHARGE:
            return freecharge()
        if self is AppProvider.MOBIKWIK:
            return mobikwik()
        if self is AppProvider.JIO:
            return jio()
