# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AuthorizationRequestAction(str, enum.Enum):
    """
    Type of authorization to run. Can be one of 'CAPTURE' , 'VOID'
    """

    CAPTURE = "CAPTURE"
    VOID = "VOID"

    def visit(self, capture: typing.Callable[[], T_Result], void: typing.Callable[[], T_Result]) -> T_Result:
        if self is AuthorizationRequestAction.CAPTURE:
            return capture()
        if self is AuthorizationRequestAction.VOID:
            return void()
