# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class AuthorizationInPaymentsEntityStatus(str, enum.Enum):
    """
    One of SUCCESS or PENDING
    """

    SUCCESS = "SUCCESS"
    PENDING = "PENDING"

    def visit(self, success: typing.Callable[[], T_Result], pending: typing.Callable[[], T_Result]) -> T_Result:
        if self is AuthorizationInPaymentsEntityStatus.SUCCESS:
            return success()
        if self is AuthorizationInPaymentsEntityStatus.PENDING:
            return pending()
