# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CardEmiCardBankName(str, enum.Enum):
    """
    Card bank name, required for EMI payments. This is the bank user has selected for EMI. One of ["hdfc, "kotak", "icici", "rbl", "bob", "standard chartered", "axis", "au", "yes", "sbi", "fed", "hsbc", "citi", "amex"]
    """

    HDFC = "hdfc"
    KOTAK = "kotak"
    ICICI = "icici"
    RBL = "rbl"
    BOB = "bob"
    STANDARD_CHARTERED = "standard chartered"
    AXIS = "axis"
    AU = "au"
    YES = "yes"
    SBI = "sbi"
    FED = "fed"
    HSBC = "hsbc"
    CITI = "citi"
    AMEX = "amex"

    def visit(
        self,
        hdfc: typing.Callable[[], T_Result],
        kotak: typing.Callable[[], T_Result],
        icici: typing.Callable[[], T_Result],
        rbl: typing.Callable[[], T_Result],
        bob: typing.Callable[[], T_Result],
        standard_chartered: typing.Callable[[], T_Result],
        axis: typing.Callable[[], T_Result],
        au: typing.Callable[[], T_Result],
        yes: typing.Callable[[], T_Result],
        sbi: typing.Callable[[], T_Result],
        fed: typing.Callable[[], T_Result],
        hsbc: typing.Callable[[], T_Result],
        citi: typing.Callable[[], T_Result],
        amex: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is CardEmiCardBankName.HDFC:
            return hdfc()
        if self is CardEmiCardBankName.KOTAK:
            return kotak()
        if self is CardEmiCardBankName.ICICI:
            return icici()
        if self is CardEmiCardBankName.RBL:
            return rbl()
        if self is CardEmiCardBankName.BOB:
            return bob()
        if self is CardEmiCardBankName.STANDARD_CHARTERED:
            return standard_chartered()
        if self is CardEmiCardBankName.AXIS:
            return axis()
        if self is CardEmiCardBankName.AU:
            return au()
        if self is CardEmiCardBankName.YES:
            return yes()
        if self is CardEmiCardBankName.SBI:
            return sbi()
        if self is CardEmiCardBankName.FED:
            return fed()
        if self is CardEmiCardBankName.HSBC:
            return hsbc()
        if self is CardEmiCardBankName.CITI:
            return citi()
        if self is CardEmiCardBankName.AMEX:
            return amex()
