# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CardCardBankName(str, enum.Enum):
    """
    One of ["Kotak", "ICICI", "RBL", "BOB", "Standard Chartered"]. Card bank name, required for EMI payments. This is the bank user has selected for EMI
    """

    KOTAK = "Kotak"
    ICICI = "ICICI"
    RBL = "RBL"
    BOB = "BOB"
    STANDARD_CHARTERED = "Standard Chartered"

    def visit(
        self,
        kotak: typing.Callable[[], T_Result],
        icici: typing.Callable[[], T_Result],
        rbl: typing.Callable[[], T_Result],
        bob: typing.Callable[[], T_Result],
        standard_chartered: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is CardCardBankName.KOTAK:
            return kotak()
        if self is CardCardBankName.ICICI:
            return icici()
        if self is CardCardBankName.RBL:
            return rbl()
        if self is CardCardBankName.BOB:
            return bob()
        if self is CardCardBankName.STANDARD_CHARTERED:
            return standard_chartered()
