# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CashbackDetailsCashbackType(str, enum.Enum):
    """
    Type of discount
    """

    FLAT = "flat"
    PERCENTAGE = "percentage"

    def visit(self, flat: typing.Callable[[], T_Result], percentage: typing.Callable[[], T_Result]) -> T_Result:
        if self is CashbackDetailsCashbackType.FLAT:
            return flat()
        if self is CashbackDetailsCashbackType.PERCENTAGE:
            return percentage()
