# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CreateRefundRequestRefundSpeed(str, enum.Enum):
    """
    Speed at which the refund is processed. It's an optional field with default being STANDARD
    """

    STANDARD = "STANDARD"
    INSTANT = "INSTANT"

    def visit(self, standard: typing.Callable[[], T_Result], instant: typing.Callable[[], T_Result]) -> T_Result:
        if self is CreateRefundRequestRefundSpeed.STANDARD:
            return standard()
        if self is CreateRefundRequestRefundSpeed.INSTANT:
            return instant()
