# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime


class EmiPlansArray(pydantic.BaseModel):
    tenure: typing.Optional[int]
    interest_rate: typing.Optional[int]
    currency: typing.Optional[str] = pydantic.Field(
        description=('<span style="white-space: nowrap">`<= 50 characters`</span>\n')
    )
    emi: typing.Optional[int]
    total_interest: typing.Optional[int]
    total_amount: typing.Optional[int]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
