# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .fetch_settlement_data_item import FetchSettlementDataItem


class FetchSettlement(pydantic.BaseModel):
    cursor: typing.Optional[str] = pydantic.Field(
        description=("Specify a value from where you want to fetch the settlement details in the API call.\n")
    )
    limit: typing.Optional[int] = pydantic.Field(
        description=("Specify the number of settlements you want to fetch in the API call.\n")
    )
    data: typing.Optional[typing.List[FetchSettlementDataItem]]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
