# This file was auto-generated by Fern from our API Definition.

import typing

from .offer_all import OfferAll
from .offer_card import OfferCard
from .offer_emi import OfferEmi
from .offer_nb import OfferNb
from .offer_paylater import OfferPaylater
from .offer_upi import OfferUpi
from .offer_wallet import OfferWallet

OfferValidationsPaymentMethod = typing.Union[
    OfferAll, OfferCard, OfferNb, OfferWallet, OfferUpi, OfferPaylater, OfferEmi
]
