# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OfferDetailsOfferType(str, enum.Enum):
    """
    Offer Type for the Offer.
    """

    DISCOUNT = "DISCOUNT"
    CASHBACK = "CASHBACK"
    DISCOUNT_AND_CASHBACK = "DISCOUNT_AND_CASHBACK"
    NO_COST_EMI = "NO_COST_EMI"

    def visit(
        self,
        discount: typing.Callable[[], T_Result],
        cashback: typing.Callable[[], T_Result],
        discount_and_cashback: typing.Callable[[], T_Result],
        no_cost_emi: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is OfferDetailsOfferType.DISCOUNT:
            return discount()
        if self is OfferDetailsOfferType.CASHBACK:
            return cashback()
        if self is OfferDetailsOfferType.DISCOUNT_AND_CASHBACK:
            return discount_and_cashback()
        if self is OfferDetailsOfferType.NO_COST_EMI:
            return no_cost_emi()
