# This file was auto-generated by Fern from our API Definition.

import typing

from .app_payment_method import AppPaymentMethod
from .card_emi_payment_method import CardEmiPaymentMethod
from .card_payment_method import CardPaymentMethod
from .cardless_emi_payment_method import CardlessEmiPaymentMethod
from .net_banking_payment_method import NetBankingPaymentMethod
from .paylater_payment_method import PaylaterPaymentMethod
from .upi_payment_method import UpiPaymentMethod

OrderPayRequestPaymentMethod = typing.Union[
    CardPaymentMethod,
    UpiPaymentMethod,
    NetBankingPaymentMethod,
    AppPaymentMethod,
    CardEmiPaymentMethod,
    CardlessEmiPaymentMethod,
    PaylaterPaymentMethod,
]
