# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OrderPayResponseAction(str, enum.Enum):
    """
    One of ["link", "custom", "form"]
    """

    LINK = "link"
    CUSTOM = "custom"
    FORM = "form"

    def visit(
        self,
        link: typing.Callable[[], T_Result],
        custom: typing.Callable[[], T_Result],
        form: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is OrderPayResponseAction.LINK:
            return link()
        if self is OrderPayResponseAction.CUSTOM:
            return custom()
        if self is OrderPayResponseAction.FORM:
            return form()
