# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OrderPayResponseChannel(str, enum.Enum):
    """
    One of ["link", "collect", "qrcode"]. In an older version we used to support different channels like 'gpay', 'phonepe' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as 'link' and provider as 'gpay'
    """

    LINK = "link"
    COLLECT = "collect"
    QRCODE = "qrcode"

    def visit(
        self,
        link: typing.Callable[[], T_Result],
        collect: typing.Callable[[], T_Result],
        qrcode: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is OrderPayResponseChannel.LINK:
            return link()
        if self is OrderPayResponseChannel.COLLECT:
            return collect()
        if self is OrderPayResponseChannel.QRCODE:
            return qrcode()
