# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OtpResponseEntityAction(str, enum.Enum):
    """
    The action that was invoked for this request.
    """

    SUBMIT_OTP = "SUBMIT_OTP"
    RESEND_OTP = "RESEND_OTP"

    def visit(self, submit_otp: typing.Callable[[], T_Result], resend_otp: typing.Callable[[], T_Result]) -> T_Result:
        if self is OtpResponseEntityAction.SUBMIT_OTP:
            return submit_otp()
        if self is OtpResponseEntityAction.RESEND_OTP:
            return resend_otp()
