# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class OtpRequestAction(str, enum.Enum):
    """
    The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
    """

    SUBMIT_OTP = "SUBMIT_OTP"
    RESEND_OTP = "RESEND_OTP"

    def visit(self, submit_otp: typing.Callable[[], T_Result], resend_otp: typing.Callable[[], T_Result]) -> T_Result:
        if self is OtpRequestAction.SUBMIT_OTP:
            return submit_otp()
        if self is OtpRequestAction.RESEND_OTP:
            return resend_otp()
