# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PaylaterProvider(str, enum.Enum):
    """
    One of ["kotak", "flexipay", "zestmoney", "lazypay", "olapostpaid","simpl", "freechargepaylater"]. Please note that Flexipay is offered by HDFC bank
    """

    KOTAK = "kotak"
    FLEXIPAY = "flexipay"
    ZESTMONEY = "zestmoney"
    LAZYPAY = "lazypay"
    OLAPOSTPAID = "olapostpaid"
    SIMPL = "simpl"
    FREECHARGEPAYLATER = "freechargepaylater"

    def visit(
        self,
        kotak: typing.Callable[[], T_Result],
        flexipay: typing.Callable[[], T_Result],
        zestmoney: typing.Callable[[], T_Result],
        lazypay: typing.Callable[[], T_Result],
        olapostpaid: typing.Callable[[], T_Result],
        simpl: typing.Callable[[], T_Result],
        freechargepaylater: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is PaylaterProvider.KOTAK:
            return kotak()
        if self is PaylaterProvider.FLEXIPAY:
            return flexipay()
        if self is PaylaterProvider.ZESTMONEY:
            return zestmoney()
        if self is PaylaterProvider.LAZYPAY:
            return lazypay()
        if self is PaylaterProvider.OLAPOSTPAID:
            return olapostpaid()
        if self is PaylaterProvider.SIMPL:
            return simpl()
        if self is PaylaterProvider.FREECHARGEPAYLATER:
            return freechargepaylater()
