# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class RefundsEntityRefundMode(str, enum.Enum):
    """
    Method or speed of processing refund
    """

    STANDARD = "STANDARD"
    INSTANT = "INSTANT"

    def visit(self, standard: typing.Callable[[], T_Result], instant: typing.Callable[[], T_Result]) -> T_Result:
        if self is RefundsEntityRefundMode.STANDARD:
            return standard()
        if self is RefundsEntityRefundMode.INSTANT:
            return instant()
