# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime


class TerminalResponse(pydantic.BaseModel):
    added_on: typing.Optional[str]
    cf_terminal_id: typing.Optional[str]
    last_updated_on: typing.Optional[str]
    terminal_area: typing.Optional[str]
    teminal_id: typing.Optional[str]
    terminal_name: typing.Optional[str]
    terminal_note: typing.Optional[str]
    terminal_phone_no: typing.Optional[str]
    terminal_status: typing.Optional[str]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
