# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime


class TerminalDetails(pydantic.BaseModel):
    terminal_phone_no: str = pydantic.Field(
        description=('Phone no assigned to the terminal <span style="white-space: nowrap">`<= 10 characters`</span> \n')
    )
    terminal_id: str = pydantic.Field(
        description=(
            'The internal id that you use to map the terminal in your internal system <span style="white-space: nowrap">`<= 100 characters`</span> \n'
        )
    )
    terminal_type: str = pydantic.Field(
        description=(
            'To identify the type of terminal product in use, in this case it is SPOS <span style="white-space: nowrap">`<= 10 characters`</span> \n'
        )
    )

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
