# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class UpiChannel(str, enum.Enum):
    """
    Specify the channel through which the payment must be processed. Can be one of ["link", "collect", "qrcode"]
    """

    LINK = "link"
    COLLECT = "collect"
    QRCODE = "qrcode"

    def visit(
        self,
        link: typing.Callable[[], T_Result],
        collect: typing.Callable[[], T_Result],
        qrcode: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is UpiChannel.LINK:
            return link()
        if self is UpiChannel.COLLECT:
            return collect()
        if self is UpiChannel.QRCODE:
            return qrcode()
