# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic

from ..core.datetime_utils import serialize_datetime
from .w_hpayment_method import WHpaymentMethod


class WHpayment(pydantic.BaseModel):
    cf_payment_id: typing.Optional[str]
    payment_status: typing.Optional[str]
    payment_amount: typing.Optional[float]
    payment_currency: typing.Optional[str]
    payment_message: typing.Optional[str]
    payment_time: typing.Optional[str]
    bank_reference: typing.Optional[str]
    auth_id: typing.Optional[str]
    payment_method: typing.Optional[WHpaymentMethod]
    payment_group: typing.Optional[str]

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().dict(**kwargs_with_defaults)

    class Config:
        frozen = True
        json_encoders = {dt.datetime: serialize_datetime}
