# This file was auto-generated by Fern from our API Definition.

import typing
import urllib.parse
from json.decoder import JSONDecodeError

import httpx
import pydantic

from ...core.api_error import ApiError
from ...core.jsonable_encoder import jsonable_encoder
from ...core.remove_none_from_headers import remove_none_from_headers
from ...types.eligibility_cardless_emi_request import EligibilityCardlessEmiRequest
from ...types.eligible_cardless_emi_entity import EligibleCardlessEmiEntity
from ...types.eligible_offers_entity import EligibleOffersEntity
from ...types.eligible_paylater import EligiblePaylater
from ...types.offer_filters import OfferFilters
from ...types.offer_queries import OfferQueries

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class EligibilityApIsClient:
    def __init__(
        self,
        *,
        environment: str,
        client_id: typing.Optional[str] = None,
        client_secret: typing.Optional[str] = None,
        api_version: typing.Optional[str] = None,
    ):
        self._environment = environment
        self.client_id = client_id
        self.client_secret = client_secret
        self.api_version = api_version

    def eligibility_offer(
        self, *, queries: OfferQueries, filters: typing.Optional[OfferFilters] = OMIT
    ) -> typing.List[EligibleOffersEntity]:
        _request: typing.Dict[str, typing.Any] = {"queries": queries}
        if filters is not OMIT:
            _request["filters"] = filters
        _response = httpx.request(
            "POST",
            urllib.parse.urljoin(f"{self._environment}/", "eligibility/offers"),
            json=jsonable_encoder(_request),
            headers=remove_none_from_headers(
                {
                    "x-client-id": self.client_id,
                    "x-client-secret": self.client_secret,
                    "x-api-version": self.api_version,
                }
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(typing.List[EligibleOffersEntity], _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def eligibility_cardless_emi(
        self, *, request: EligibilityCardlessEmiRequest
    ) -> typing.List[EligibleCardlessEmiEntity]:
        _response = httpx.request(
            "POST",
            urllib.parse.urljoin(f"{self._environment}/", "eligibility/cardlessemi"),
            json=jsonable_encoder(request),
            headers=remove_none_from_headers(
                {
                    "x-client-id": self.client_id,
                    "x-client-secret": self.client_secret,
                    "x-api-version": self.api_version,
                }
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(typing.List[EligibleCardlessEmiEntity], _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def eligibility_paylater(self, *, request: EligibilityCardlessEmiRequest) -> typing.List[EligiblePaylater]:
        _response = httpx.request(
            "POST",
            urllib.parse.urljoin(f"{self._environment}/", "eligibility/paylater"),
            json=jsonable_encoder(request),
            headers=remove_none_from_headers(
                {
                    "x-client-id": self.client_id,
                    "x-client-secret": self.client_secret,
                    "x-api-version": self.api_version,
                }
            ),
            timeout=60,
        )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(typing.List[EligiblePaylater], _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncEligibilityApIsClient:
    def __init__(
        self,
        *,
        environment: str,
        client_id: typing.Optional[str] = None,
        client_secret: typing.Optional[str] = None,
        api_version: typing.Optional[str] = None,
    ):
        self._environment = environment
        self.client_id = client_id
        self.client_secret = client_secret
        self.api_version = api_version

    async def eligibility_offer(
        self, *, queries: OfferQueries, filters: typing.Optional[OfferFilters] = OMIT
    ) -> typing.List[EligibleOffersEntity]:
        _request: typing.Dict[str, typing.Any] = {"queries": queries}
        if filters is not OMIT:
            _request["filters"] = filters
        async with httpx.AsyncClient() as _client:
            _response = await _client.request(
                "POST",
                urllib.parse.urljoin(f"{self._environment}/", "eligibility/offers"),
                json=jsonable_encoder(_request),
                headers=remove_none_from_headers(
                    {
                        "x-client-id": self.client_id,
                        "x-client-secret": self.client_secret,
                        "x-api-version": self.api_version,
                    }
                ),
                timeout=60,
            )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(typing.List[EligibleOffersEntity], _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def eligibility_cardless_emi(
        self, *, request: EligibilityCardlessEmiRequest
    ) -> typing.List[EligibleCardlessEmiEntity]:
        async with httpx.AsyncClient() as _client:
            _response = await _client.request(
                "POST",
                urllib.parse.urljoin(f"{self._environment}/", "eligibility/cardlessemi"),
                json=jsonable_encoder(request),
                headers=remove_none_from_headers(
                    {
                        "x-client-id": self.client_id,
                        "x-client-secret": self.client_secret,
                        "x-api-version": self.api_version,
                    }
                ),
                timeout=60,
            )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(typing.List[EligibleCardlessEmiEntity], _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def eligibility_paylater(self, *, request: EligibilityCardlessEmiRequest) -> typing.List[EligiblePaylater]:
        async with httpx.AsyncClient() as _client:
            _response = await _client.request(
                "POST",
                urllib.parse.urljoin(f"{self._environment}/", "eligibility/paylater"),
                json=jsonable_encoder(request),
                headers=remove_none_from_headers(
                    {
                        "x-client-id": self.client_id,
                        "x-client-secret": self.client_secret,
                        "x-api-version": self.api_version,
                    }
                ),
                timeout=60,
            )
        if 200 <= _response.status_code < 300:
            return pydantic.parse_obj_as(typing.List[EligiblePaylater], _response.json())  # type: ignore
        try:
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
