# This file was auto-generated by Fern from our API Definition.

import typing

from .resources.orders.client import AsyncOrdersClient, OrdersClient


class ShubhiMaheshwariApi:
    def __init__(self, *, environment: str, api_version: typing.Optional[str] = None):
        self._environment = environment
        self.api_version = api_version
        self.orders = OrdersClient(environment=self._environment, api_version=self.api_version)


class AsyncShubhiMaheshwariApi:
    def __init__(self, *, environment: str, api_version: typing.Optional[str] = None):
        self._environment = environment
        self.api_version = api_version
        self.orders = AsyncOrdersClient(environment=self._environment, api_version=self.api_version)
